spring:
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/forum?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  freemarker:
    settings:
      classic_compatible: true
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
    cache: false  # 清除缓存实现热部署
  redis:
    host: 127.0.0.1
    post: 6379
    password: myslayers
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

file:
  upload:
    dir: ${user.dir}/upload